SELECT
	*
FROM
	EMPLOYEES;

SELECT
	*
FROM
	DEPARTMENTS;

-- 1. 사원 테이블에서 사원번호가 100, 107 번인 사원번호와 이름을 출력
SELECT
	EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME
FROM
	EMPLOYEES
WHERE
	EMPLOYEE_ID IN ('100', '107');
	
SELECT
	EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME
FROM
	EMPLOYEES
WHERE
	EMPLOYEE_ID=100 OR EMPLOYEE_ID=107;
	
-- 2. 사원 테이블에서 사원번호가 100, 107 번이 아닌 사원번호와 이름을 출력
SELECT
	EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME
FROM
	EMPLOYEES
WHERE
	EMPLOYEE_ID NOT IN ('100', '107');
	
SELECT
	EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME
FROM
	EMPLOYEES
WHERE
	EMPLOYEE_ID!=100 AND EMPLOYEE_ID!=107;
	
-- 3. 사원 테이블에서 급여(SAL)가 3000에서 5000사이인 사원 정보를 출력
SELECT
	*
FROM
	EMPLOYEES
WHERE
	SALARY BETWEEN 3000 AND 5000;
	
SELECT
	*
FROM
	EMPLOYEES
WHERE
	SALARY >= 3000 AND SALARY <= 5000;

-- 4. 사원 테이블에서 고용일자가 2005/1/1 이후 고용된 사원 정보를 출력
SELECT
	*
FROM
	EMPLOYEES
WHERE
	HIRE_DATE>='2005/1/1';

-- 유사문제 : 이번달에 입사한 사원의 이름과 입사일을 출력
SELECT
	FIRST_NAME || ' ' || LAST_NAME 이름, HIRE_DATE 입사일
FROM
	EMPLOYEES
WHERE
	EXTRACT(MONTH FROM HIRE_DATE)=EXTRACT(MONTH FROM SYSDATE);

SELECT
	FIRST_NAME || ' ' || LAST_NAME 이름, HIRE_DATE 입사일
FROM
	EMPLOYEES
WHERE
	TO_CHAR(HIRE_DATE, 'yyyy-mm-dd') LIKE '%-' || EXTRACT(MONTH FROM SYSDATE) || '-%';

SELECT
	FIRST_NAME || ' ' || LAST_NAME 이름, HIRE_DATE 입사일
FROM
	EMPLOYEES
WHERE
	TO_CHAR(HIRE_DATE, 'mm') = TO_CHAR(SYSDATE, 'mm');

SELECT
	FIRST_NAME || ' ' || LAST_NAME 이름, HIRE_DATE 입사일
FROM
	EMPLOYEES
WHERE
	SUBSTR(HIRE_DATE,5,2) = SUBSTR(SYSDATE,5,2);

-- 5. 사원 테이블에서 직업이 SA_MAN 중에서 사원번호의 최대값을 출력
SELECT
	MAX(EMPLOYEE_ID) 사원번호
FROM
	EMPLOYEES
WHERE
	JOB_ID='SA_MAN';

SELECT
	MAX(EMPLOYEE_ID)
FROM
	EMPLOYEES
GROUP BY
	JOB_ID
HAVING
	JOB_ID='SA_MAN';
	
-- 6. 연봉이 12000 이상인 직원들의 LAST_NAME 및 연봉을 조회한다.
SELECT
	LAST_NAME, SALARY
FROM
	EMPLOYEES
WHERE
	SALARY>=12000;
-- 7. 사원번호가 176 이상인 직원들의 LAST_NAME 및 부서 번호를 조회한다.
SELECT
	LAST_NAME, DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	EMPLOYEE_ID='176'
-- 8. 연봉이 5000에서 12000의 번위이외인 사람들의 LAST_NAME 및 연봉을 조회한다.
SELECT
	LAST_NAME, SALARY
FROM
	EMPLOYEES
WHERE
	SALARY BETWEEN 5000 AND 12000;
-- 9. 1998/02/20부터 1998/05/01 사이에 고용된 사원들의 LAST_NAME, 사번, 고용일자를 고용일자 순으로 정렬한다.
SELECT
	LAST_NAME, EMPLOYEE_ID, HIRE_DATE
FROM
	EMPLOYEES
WHERE
	HIRE_DATE
BETWEEN
	'2002/02/20' AND '2005/01/01'
ORDER BY
	HIRE_DATE;
-- 10. 20번 및 50번 부서에서 근무하는 모든 사원들의 LAST_NAME 및 부서 번호를 알파벳순으로 조회한다.
SELECT
	LAST_NAME, DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	DEPARTMENT_ID IN (20,50)
ORDER BY
	LAST_NAME;
-- 11. 20번 및 50번 부서에 근무하며, 연봉이 5000 ~ 12,000 사이인 사원들의 LAST_NAME 및 연봉을 조회한다.
SELECT
	LAST_NAME, SALARY
FROM
	EMPLOYEES
WHERE
	DEPARTMENT_ID IN (20,50) AND SALARY BETWEEN 5000 AND 12000;
-- 12. 2002년도에 고용된 모든 사람들의 LAST_NAME 및 고용일을 조회한다.
SELECT
	FIRST_NAME || ' ' || LAST_NAME 이름, HIRE_DATE 입사일
FROM
	EMPLOYEES
WHERE
	TO_CHAR(HIRE_DATE, 'yyyy')=2002;

SELECT
	FIRST_NAME || ' ' || LAST_NAME 이름, HIRE_DATE 입사일
FROM
	EMPLOYEES
WHERE
	EXTRACT(YEAR FROM HIRE_DATE)=2002;

-- 13. 매니저가 없는 사람들의 LAST_NAME 및 JOB_ID를 조회한다.
SELECT
	FIRST_NAME || ' ' || LAST_NAME 이름, JOB_ID
FROM
	EMPLOYEES
WHERE
	MANAGER_ID IS NULL;
	
-- 14. 커미션을 버는 모든 사원들의 LAST_NAME, 연봉 및 커미션을 조회한다.
-- 연봉 역순, 커미션 역순차로 정렬한다.
SELECT
	LAST_NAME, SALARY, COMMISSION_PCT
FROM
	EMPLOYEES
WHERE
	COMMISSION_PCT IS NOT NULL
ORDER BY
	SALARY DESC, COMMISSION_PCT DESC;

-- 15. LAST_NAME의 네번째 글자가 a인 사원들의 LAST_NAME을 조회한다.
SELECT
	LAST_NAME
FROM
	EMPLOYEES
WHERE
	LAST_NAME LIKE '___a%';